name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --fatal-infos

      - name: Test
        run: flutter test

      - name: Build Android App Bundle (release)
        run: flutter build appbundle --release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 30

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --fatal-infos

      - name: Test
        run: flutter test

      # Build iOS without codesign (tạo Runner.app)
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # Đóng gói IPA unsigned với cấu trúc Payload/Runner.app
      - name: Package unsigned IPA
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          (cd build/ios/ipa && zip -r Runner-unsigned.ipa Payload)

      # Upload cả Runner.app và IPA unsigned để tham chiếu
      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-unsigned
          path: |
            build/ios/iphoneos/Runner.app
            build/ios/ipa/Runner-unsigned.ipa
          retention-days: 30
