name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger khi push tag bắt đầu bằng 'v' (ví dụ: v1.0.0)

jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android App Bundle (release)
        run: flutter build appbundle --release

      - name: Build Android APK (release)
        run: flutter build apk --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          (cd build/ios/ipa && zip -r Runner-unsigned.ipa Payload)

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ios/ipa/Runner-unsigned.ipa
          body: |
            ## iOS Build (Unsigned)
            - This is an unsigned IPA file
            - For testing purposes only
            - Cannot be installed on real devices without codesigning
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

